name: Firebase Deploy

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      # - run: npm ci
      - name: npm build
        run: npm run build
        working-directory: .frontend/

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        working-directory: .frontend/
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}